---
- name: update packages
  yum:
    name: '*'
    update_cache: true
    state: 'latest'

- name: install yum-utils
  yum: 
    name: yum-utils
    state: present

- name: add hashicorp repo
  get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.rep
    
- name: install nomad
  yum: 
    name: nomad
    state: present

- name: enable nomad
  systemd: 
    name: nomad
    state: started
    enabled: yes