{
 "title": "Website Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Memstats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes in use by mchache structure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=\"webserver\"}",
     "legendFormat": "bytes"
    }
   ]
  },
  { "title": "HTTP status counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP 503 (Service Unavailable) Responses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"503\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP 200 (OK) Responses",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"200\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}