---
- name: server preparation
  hosts: servers
  become: yes
  roles:
    - consul
    - nomad

- name: client preparation
  hosts: clients
  become: yes
  roles: 
    - consul
    - nomad
    - docker
