---
- name: update packages
  yum:
    name: '*'
    update_cache: true
    state: 'latest'

- name: install yum-utils
  yum: 
    name: yum-utils
    state: present

- name: add hashicorp repo
  get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: install consul
  yum: 
    name: consul
    state: present

- name: consul server conf
  template:
    src: server.hcl.j2
    dest: /etc/consul.d/consul.hcl
  when: is_server|bool

- name: consul client conf
  template:
    src: client.hcl.j2
    dest: /etc/consul.d/consul.hcl
  when: not is_server|bool   

- name: enable consul
  systemd:
    name: consul
    state: started
    enabled: yes